### ISSUE TITLE
"500 error" on "Variant Notes" and "Flag for Review" links

### ISSUE THREAD

**Issue by monkollek** [macarthur-lab/xbrowse#106]
Can we have a more informative error page be displayed here or have some checks to make sure this link works for each project.

**Comment by bw2** [comment]
Looking into this, the I can see the error on the website, and see the request appear in the logs as "GET /xbrowse/project/newcastle/variant-notes HTTP/1.1" 500"  but there's no django error message. Also, I can't reproduce this error on my local dev. instance.  @brettpthomas do you have any suggestions for this? If not, I will try turning on DEBUG=True tomorrow.

**Comment by bw2** [comment]
Fixed on the ATGU server
