### ISSUE TITLE
Add direct link to ExAC browser for all variants in search results table

### ISSUE THREAD

**Issue by dgmacarthur** [macarthur-lab/xbrowse#120]
Pretty self-explanatory and hopefully straightforward - just a link to the ExAC variant page if the variant does indeed exist there. One possibility would be to have this as a hyperlink for the ExAC frequency entry.

**Comment by brettpthomas** [comment]
Done! The frequency is hyperlinked if variant is in exac (eg. the decimal is > 0) and just plain text if not.
