### ISSUE TITLE
Need to distinguish between ClinVar annotations

### ISSUE THREAD

**Issue by dgmacarthur** [macarthur-lab/xbrowse#122]
Simply knowing a variant is in ClinVar isn't especially useful as many are marked as benign or likely benign.

I suggest we only flag ClinVar variants marked as pathogenic or likely pathogenic. Alternatively we could use a color scheme:

green = benign or likely benign
yellow = variant of uncertain significance
red = pathogenic or likely pathogenic

**Comment by bw2** [comment]
if a variant is both benign and pathogenic we can flash between the colors... just need help choosing the speed.

**Comment by bw2** [comment]
fixed the colors as suggested except "uncertain significance" is just bold gray, and "risk factor" is orange.
