### ISSUE TITLE
ec2 puppet installation issue

### ISSUE THREAD

**Issue by matthdsm** [macarthur-lab/xbrowse#149]
Hi

we are trying create a local install of xBrowse on our local cloud using your ec2 puppet manifests. During the installation process, we get the following issue:

    Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
    Warning: Variable access via 'raw_data_dir' is deprecated. Use '@raw_data_dir' instead. template[/mnt/code/xbrowse/deploy/puppet/modules/xbrowse_settings/templates/custom_annotator_settings.py]:6
        (at /usr/lib/ruby/site_ruby/1.8/puppet/parser/templatewrapper.rb:77:in `method_missing')
    Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class django at /mnt/code/xbrowse/deploy/puppet/modules/base/manifests/init.pp:40 on node xbrowse
    Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class django at /mnt/code/xbrowse/deploy/puppet/modules/base/manifests/init.pp:40 on node xbrowse
    
It seems the "django" class isn't declared anywhere in your code. Perhaps an error in commiting your code?

Greetings
Matthias

**Comment by kgutwin** [comment]
Commit 68e76f31bc41a480d92db6792fdf64ff42c10922 removed `deploy/puppet/modules/django/manifests/init.pp`; commit 4fae4517021340a8f81cbed38f1be8428b659f60 ostensibly reverted the changes in 68e76f31bc41a480d92db6792fdf64ff42c10922 but didn't re-add that file.

**Comment by bw2** [comment]
the most up-to-date install instructions can be found at
https://github.com/macarthur-lab/xbrowse/blob/master/deploy/mac_osx/README.md
