### ISSUE TITLE
Search all cohorts for a variant

### ISSUE THREAD

**Issue by berylc** [macarthur-lab/xbrowse#154]
It would be great to see if a variant exists in any of the cohorts we're able to access in xBrowse. Especially useful if 1) if variant is not covered in ExAC 2) for whole genome data. 

e.g. want to see if chr2:152439984 G>A  is seen in any other patient (http://exac.broadinstitute.org/region/2-152439970-152439990)

**Comment by evalkanas** [comment]
moved to xbrowse2 issues
