### ISSUE TITLE
Create a workflow for uploading samples from the GP to xBrowse

### ISSUE THREAD

**Issue by evalkanas** [macarthur-lab/xbrowse#155]
We need a better system for making sure all data in call sets gets imported to xBrowse. Some samples have been falling through the cracks (WGS, small external WES projects, etc).

**Comment by evalkanas** [comment]
Also think about how this will get communicated down the line (from PM saying the call set is ready to samples being on xBrowse)

**Comment by bw2** [comment]
Now taken care thanks to Hayley.
