### ISSUE TITLE
Include HGVS in VEP output 

### ISSUE THREAD

**Issue by brettpthomas** [macarthur-lab/xbrowse#39]

**Comment by brettpthomas** [comment]
This has been identified as an urgent need by multiple collaborators. In previous tests, adding all VEP annotations was prohibitively slow, so we need a better way to parallelize annotations.

**Comment by bw2** [comment]
Now running VEP with --everything, which includes --hgvs

**Comment by bw2** [comment]
Issue #131 created for adding HGVS to the results view
