### ISSUE TITLE
no module named slugify

### ISSUE THREAD

**Issue by leondeng402** [macarthur-lab/xbrowse#59]
in parsers package, fam_stuff.py import slugify: 
Import Error: no module named slugify

**Comment by gpcr** [comment]
Facing below error: please do suggest to overcome

xbrowse/__init__.py", line 20, in <module>
    from .parsers import fam_stuff
xbrowse/parsers/fam_stuff.py", line 2, in <module>
    import slugify

**Comment by brettpthomas** [comment]
@gpcr try `pip install awesome-slugify==1.6`. 

This is in our requirements file - `server_requirements.txt` - let us know if for some reason that didn't install.

**Comment by gpcr** [comment]
@brettpthomas thanks ; got above error when trying to install exac_browser, now it is rectified. May be its is not updated in their pull.
