### ISSUE TITLE
Add a link to ClinVar entry

### ISSUE THREAD

**Issue by ericminikel** [macarthur-lab/xbrowse#64]

**Comment by bw2** [comment]
http://www.ncbi.nlm.nih.gov/clinvar/docs/linking/

Can use accenssion (eg. http://www.ncbi.nlm.nih.gov/clinvar/RCV000007523/)

What's the correct way to handle a variant that has 2 accession #s in the clinvar VCF?
For example:
chr9:135779106  GGGCAT>G    has   RCV000042159.2,  RCV000042160.2

with links:
http://www.ncbi.nlm.nih.gov/clinvar/RCV000042159.2
http://www.ncbi.nlm.nih.gov/clinvar/RCV000042160.2

**Comment by bw2** [comment]
Here's what these variants look like in the clinvar vcf:

tabix ../../data/reference_data/clinvar/clinvar.vcf.gz 9:135779105-135779107
```9	135779106	rs118203648	GGGCAT	G	.	.	RS=118203648;RSPOS=135779108;RV;dbSNPBuildID=132;SSR=0;SAO=0;VP=0x050168001205000002100200;GENEINFO=TSC1:7248;WGT=1;VC=DIV;PM;PMC;SLO;NSF;REF;ASP;LSD;CLNALLE=1;CLNHGVS=NC_000009.11:g.135779108_135779112delGCATG;CLNSRC=Tuberous_sclerosis_database_(TSC1);CLNORIGIN=1;CLNSRCID=TSC1_00362;CLNSIG=1;CLNDSDB=GeneReviews:MedGen:OMIM:SNOMED_CT;CLNDSDBID=NBK1220:C0041341:191100:7199000;CLNDBN=Tuberous_sclerosis_syndrome;CLNREVSTAT=not;CLNACC=RCV000042159.2
```
```9	135779106	rs118203649	GGGCAT	G	.	.	RS=118203649;RSPOS=135779107;RV;dbSNPBuildID=132;SSR=0;SAO=0;VP=0x050160001205000002100200;GENEINFO=TSC1:7248;WGT=1;VC=DIV;PM;SLO;NSF;REF;ASP;LSD;CLNALLE=1;CLNHGVS=NC_000009.11:g.135779107_135779111delGGCAT;CLNSRC=Tuberous_sclerosis_database_(TSC1);CLNORIGIN=1;CLNSRCID=TSC1_00139;CLNSIG=1;CLNDSDB=GeneReviews:MedGen:OMIM:SNOMED_CT;CLNDSDBID=NBK1220:C0041341:191100:7199000;CLNDBN=Tuberous_sclerosis_syndrome;CLNREVSTAT=not;CLNACC=RCV000042160.2```

**Comment by bw2** [comment]
There  274 (out of 112814)  of these duplicate variants in the clinvar VCF.

**Comment by ericminikel** [comment]
Glad you bring this up. In addition to this type of dup (>1 consecutive row with the same variant), I found two other dup situations:

+ A single row but in the INFO field, `CLNALLE=1,1` and then `CLNACC=RCV1,RCV2`
+ Both the REF and ALT are in ClinVar, represented by `CLNALLE=0,1` (not strictly speaking a dup, but still hard to figure out how to represent)

You can see how I handled these here: https://github.com/macarthur-lab/exac_papers/blob/master/src/parse_clinvar.py

In my case, for the ExAC analyses we are mostly interested in reportedly pathogenic variants, so I took the RCV number associated with the highest review status and most pathogenic assertion. xBrowse's needs might be the same, or it might be preferred to include all of the RCVs so the user can decide. If you can figure out an elegant way to include all of them, I'd do it, but if it's going to really clutter the interface, then maybe it's worth whittling down to one RCV per variant.
