### ISSUE TITLE
VEP cache dir is incorrect in Puppet deployment 

### ISSUE THREAD

**Issue by brettpthomas** [macarthur-lab/xbrowse#83]

**Comment by bw2** [comment]
Also have this issue in the mac_osx install. 

I think we should take VEP and the VEP cache out of the resource bundle (@brettpthomas you told me the reason it was in there at one point, but I've forgotten what it is), and just install it directly from:
http://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html?redirect=no#versions

The VEP Install.pl script then has command-line options which we can use to download and install the cache:
```
-d | --DESTDIR     Set destination directory for API install (default = './')
-c | --CACHEDIR    Set destination directory for cache files (default = '/.vep/')
-u | --UPDATE      EXPERIMENTAL! Check for and download new VEP versions
-a | --AUTO        Run installer without user prompts. Use a (API), c (cache),
                   f (FASTA) to specify parts to install e.g. -a ac for API and
                   cache
-s | --SPECIES     Comma-separated list of species to install when using --AUTO
```
